### ISSUE TITLE
依赖包缺少build

### ISSUE THREAD

**Issue by qiuliang1** [WebEngineerLi/react-captcha#10]
react-captcha-code@1.0.6

依赖包中缺少build，即使添加声明文件在编译过程中会报错找不到该模块
![image](https://user-images.githubusercontent.com/35951262/108930283-9b665b00-7680-11eb-8591-2c0e0c7f4844.png)

https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/package.json

在codesandbox中也发现报错没有找到模块问题，将版本回退到v1.0.5正常显示
麻烦您解决下此问题，感谢

**Comment by WebEngineerLi** [comment]
https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/src/controlled.tsx 已修复 1.0.7可用

**Comment by WebEngineerLi** [comment]
https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/src/controlled.tsx 已修复 1.0.7可用
