### ISSUE TITLE
如何获取验证码字符

### ISSUE THREAD

**Issue by JianTin** [WebEngineerLi/react-captcha#17]
看了下API，好像没提供获取验证码内部字符的方法。

**Comment by WebEngineerLi** [comment]
> 看了下API，好像没提供获取验证码内部字符的方法。

非受控可以通过回调函数 `onChange` 拿到内部字符，具体可以看这个 [DEMO](https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/src/uncontrolled.tsx:476-484)
