### ISSUE TITLE
antd pro的ProFrom中使用,refresh不起作用

### ISSUE THREAD

**Issue by darkfiredarkhalo** [WebEngineerLi/react-captcha#20]
`antd pro`的[ProFrom](https://procomponents.ant.design/components/form)中使用,`refresh`不起作用  
```
<ProForm>
     ...
     <ProForm.Item
          name="code"
          rules={[
            {
              required: true,
              message: '请输入图形码!',
            },
          ]}
        >
                <div className={styles.imgCodeBox}>
                  <Input
                    placeholder="请输入图形码"
                    prefix={<RobotOutlined />}
                    className="ant-input-lg"
                  />
                  <Captcha
                    ref={captchaRef}
                    charNum={4}
                    onClick={onCodeClick}
                    className={styles.code}
                  />
                </div>
     </ProForm.Item>
    ...
</ProForm>
```

**Comment by darkfiredarkhalo** [comment]
我错了, 有受控的解决方案, 不好意思哈

**Comment by WebEngineerLi** [comment]
https://codesandbox.io/s/jibenshiyong-forked-0otkn?file=/App.tsx

**Comment by WebEngineerLi** [comment]
https://codesandbox.io/s/jibenshiyong-forked-0otkn?file=/App.tsx
非受控也可以哦。
![image](https://user-images.githubusercontent.com/30517805/122028029-333daf80-cdfe-11eb-9ceb-0b332d96cf5e.png)
onClick -> onChange 即可

**Comment by darkfiredarkhalo** [comment]
就是自己控制"code"的值是吧

**Comment by WebEngineerLi** [comment]
> 就是自己控制"code"的值是吧
不是的，你看一下我给你的这个 Demo
https://codesandbox.io/s/jibenshiyong-forked-0otkn?file=/App.tsx
onChange 会暴漏出来当前组件内部的 code

**Comment by WebEngineerLi** [comment]
> `antd pro`的[ProFrom](https://procomponents.ant.design/components/form)中使用,`refresh`不起作用
> 
> ```
> <ProForm>
>      ...
>      <ProForm.Item
>           name="code"
>           rules={[
>             {
>               required: true,
>               message: '请输入图形码!',
>             },
>           ]}
>         >
>                 <div className={styles.imgCodeBox}>
>                   <Input
>                     placeholder="请输入图形码"
>                     prefix={<RobotOutlined />}
>                     className="ant-input-lg"
>                   />
>                   <Captcha
>                     ref={captchaRef}
>                     charNum={4}
>                     onClick={onCodeClick}
>                     className={styles.code}
>                   />
>                 </div>
>      </ProForm.Item>
>     ...
> </ProForm>
> ```

1. 默认情况下直接点验证码这个 canvas 是可以切换验证码的，当前的验证码会通过 onChange 函数传递出来
2. 之所以加一个 `refresh` 是为了满足点击一个按钮(类似于“点击切换验证码的按钮”)，来让验证码刷新一遍的

**Comment by darkfiredarkhalo** [comment]
😱, 这是什么原理呢? 只要有`onChange`就可以了,太神奇了

**Comment by darkfiredarkhalo** [comment]
> > `antd pro`的[ProFrom](https://procomponents.ant.design/components/form)中使用,`refresh`不起作用
> > ```
> > <ProForm>
> >      ...
> >      <ProForm.Item
> >           name="code"
> >           rules={[
> >             {
> >               required: true,
> >               message: '请输入图形码!',
> >             },
> >           ]}
> >         >
> >                 <div className={styles.imgCodeBox}>
> >                   <Input
> >                     placeholder="请输入图形码"
> >                     prefix={<RobotOutlined />}
> >                     className="ant-input-lg"
> >                   />
> >                   <Captcha
> >                     ref={captchaRef}
> >                     charNum={4}
> >                     onClick={onCodeClick}
> >                     className={styles.code}
> >                   />
> >                 </div>
> >      </ProForm.Item>
> >     ...
> > </ProForm>
> > ```
> 
> 1. 默认情况下直接点验证码这个 canvas 是可以切换验证码的，当前的验证码会通过 onChange 函数传递出来
> 2. 之所以加一个 `refresh` 是为了满足点击一个按钮(类似于“点击切换验证码的按钮”)，来让验证码刷新一遍的

非常感谢, 我太菜了😭

**Comment by WebEngineerLi** [comment]
> 😱, 这是什么原理呢? 只要有`onChange`就可以了,太神奇了

https://github.com/WebEngineerLi/react-captcha/blob/66f540009e908e677fb77596b2529bc862785940/src/captcha.tsx#L137
我在组件内部监听了 canvas 的 `click`，然后调用了 `onChange`，把code传出来了，原理就是这么简单。

**Comment by darkfiredarkhalo** [comment]
👍🏻, 太厉害了, 有时间得学习下, 非常感谢, 让项目做起来又简便了许多, 👍🏻
