### ISSUE TITLE
希望可以暴露一个刷新接口

### ISSUE THREAD

**Issue by David2k13** [WebEngineerLi/react-captcha#4]
希望可以暴露一个刷新接口

**Comment by WebEngineerLi** [comment]
> 希望可以暴露一个刷新接口

已更新，可查看 [demo](https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.tsx)

**Comment by David2k13** [comment]
nice，看起来是可以工作了，个人一点小意见：useEffect(() => {
    onRef(canvas)
  }, [])，你这样onRef就是一个必填项了，用useImperativeHandle是不是更加安全呢

**Comment by WebEngineerLi** [comment]
> useImperativeHandle

**Comment by WebEngineerLi** [comment]
> nice，看起来是可以工作了，个人一点小建议：useEffect(() => {
> onRef(canvas)
> }, [])，你这样onRef就是一个必填项了，用useImperativeHandle是不是更加安全呢

感谢老哥的建议，学习了`useImperativeHandle`的用法，我抽空改一下呢

**Comment by David2k13** [comment]
nice
