### ISSUE TITLE
我们有个需求是用后台返回的校验码展示，而不是用自动生成的，这个有属性支持吗？

### ISSUE THREAD

**Issue by qingfengmy** [WebEngineerLi/react-captcha#8]

**Comment by WebEngineerLi** [comment]
现在这个验证码组件是非受控的，我抽空支持一下受控

**Comment by WebEngineerLi** [comment]
https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/src/controlled.tsx 已支持

**Comment by WebEngineerLi** [comment]
https://codesandbox.io/s/zen-paper-9yish?fontsize=14&hidenavigation=1&theme=dark&file=/src/controlled.tsx 已支持
